### ISSUE TITLE
"doOverlap" is misleading

### ISSUE THREAD

**Issue by bkaestner** [I3ck/HGE2D#3]
Judging by its name, `doOverlap` should return true if the bounding boxes overlap, e.g. on

![overlapping boxes](https://cloud.githubusercontent.com/assets/6301773/13014094/71e95930-d1b2-11e5-849a-c4a6bf6076cc.png)

However, the [current implementation](https://github.com/I3ck/HGE2D/blob/master/src/HGE2D/Collision.hs#L29-L31) returns `False`, since neither the green box is contained in the grey one nor vice versa. If this is intended, the name should probably get changed.

**Comment by I3ck** [comment]
fixed with https://github.com/I3ck/HGE2D/commit/a72e5bd9ccc920c066e04597ce76356ef4c25b41
thanks

**Comment by bkaestner** [comment]
About the version bump: I don't think it's necessary as long as you don't upload your library it to hackage. You're still at a very experimental stage.

**Comment by I3ck** [comment]
I'll bump the version whenever the interface to the lib changes. Which a rename of a function surely causes
